DROP USER webmarket CASCADE; 
CREATE USER webmarket IDENTIFIED BY webmarket1234 DEFAULT TABLESPACE users TEMPORARY
TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO webmarket;
GRANT CREATE VIEW, CREATE SYNONYM TO webmarket;
ALTER USER webmarket ACCOUNT UNLOCK;