DROP USER JSPBook CASCADE; 
CREATE USER JSPBook IDENTIFIED BY web1234 DEFAULT TABLESPACE users TEMPORARY
TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO JSPBook;
GRANT CREATE VIEW, CREATE SYNONYM TO JSPBook;
ALTER USER JSPBook ACCOUNT UNLOCK;